
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gloriamadhri
 */
public class Addcontact extends javax.swing.JFrame {

    /**
     * Creates new form Addcontact
     */
    Connection conn;
    public Addcontact() {
      conn = DB.dbconnect();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Bsubmit = new javax.swing.JButton();
        TaddName = new javax.swing.JTextField();
        TaddNumber = new javax.swing.JTextField();
        TaddSurname = new javax.swing.JTextField();
        TaddAddress = new javax.swing.JTextField();
        TaddEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Bback = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jTextField3.setText("jTextField3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bsubmit.setBackground(new java.awt.Color(50, 90, 146));
        Bsubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bsubmit.setText("Submit");
        Bsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Bsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 90, -1));

        TaddName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaddNameActionPerformed(evt);
            }
        });
        getContentPane().add(TaddName, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 60, 137, 28));

        TaddNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaddNumberActionPerformed(evt);
            }
        });
        getContentPane().add(TaddNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 156, 137, 29));

        TaddSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaddSurnameActionPerformed(evt);
            }
        });
        getContentPane().add(TaddSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 106, 137, 32));

        TaddAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaddAddressActionPerformed(evt);
            }
        });
        getContentPane().add(TaddAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 203, 137, 28));

        TaddEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaddEmailActionPerformed(evt);
            }
        });
        getContentPane().add(TaddEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 249, 137, 32));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 60, 108, 28));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("SURNAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 106, 108, 32));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setText("EMAIL ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 249, 108, 32));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setText("ADDRESS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 203, 108, 28));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setText("NUMBER");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 156, 108, 29));

        Bback.setBackground(new java.awt.Color(50, 90, 146));
        Bback.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bback.setText("Back");
        Bback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbackActionPerformed(evt);
            }
        });
        getContentPane().add(Bback, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 80, -1));

        jPanel3.setBackground(new java.awt.Color(255, 204, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(50, 90, 146));
        jLabel1.setText("ADD CONTACTS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 406, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 410, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsubmitActionPerformed
        try {
            // TODO add your handling code here:
            String addNumber = TaddNumber.getText();
            String addEmail = TaddEmail.getText();
            String addName = TaddName.getText();
            String addSurname = TaddSurname.getText();
            String addAdress = TaddAddress.getText();
            PreparedStatement pst=conn.prepareStatement("insert into person(name,surname,num,adress,email) values(?,?,?,?,?)");
            pst.setString(1, addName);
            pst.setString(2, addSurname);
            pst.setString(3, addNumber);
            pst.setString(4, addAdress);
            pst.setString(5, addEmail);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "added successfully");
            view1 v3 = new view1();
            v3.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Addcontact.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BsubmitActionPerformed

    private void BbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbackActionPerformed
        // TODO add your handling code here:
        view1 v3 = new view1();
        v3.setVisible(true);
    }//GEN-LAST:event_BbackActionPerformed

    private void TaddNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaddNumberActionPerformed
        // TODO add your handling code here:
        String addNumber = TaddNumber.getText();
    }//GEN-LAST:event_TaddNumberActionPerformed

    private void TaddEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaddEmailActionPerformed
        // TODO add your handling code here:
        String addEmail = TaddEmail.getText();
    }//GEN-LAST:event_TaddEmailActionPerformed

    private void TaddNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaddNameActionPerformed
        // TODO add your handling code here:
        String addName = TaddName.getText();
    }//GEN-LAST:event_TaddNameActionPerformed

    private void TaddSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaddSurnameActionPerformed
        // TODO add your handling code here:
        String addSurname = TaddSurname.getText();
    }//GEN-LAST:event_TaddSurnameActionPerformed

    private void TaddAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaddAddressActionPerformed
        // TODO add your handling code here:
        String addAdress = TaddAddress.getText();
    }//GEN-LAST:event_TaddAddressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addcontact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addcontact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addcontact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addcontact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addcontact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bback;
    private javax.swing.JButton Bsubmit;
    private javax.swing.JTextField TaddAddress;
    private javax.swing.JTextField TaddEmail;
    private javax.swing.JTextField TaddName;
    private javax.swing.JTextField TaddNumber;
    private javax.swing.JTextField TaddSurname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
